server:
  port: 8080

spring:
  main:
    banner-mode: off   # Disable the ASCII Spring banner

  datasource:
    username: root
    password: 12345678
    url: jdbc:mysql://localhost:3306/trivia
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: false       # Turn off printing SQL statements
    properties:
      hibernate:
        format_sql: false
    hibernate:
      ddl-auto: update

logging:
  level:
    root: WARN            # Only show WARN and ERROR logs overall
    org.hibernate: WARN   # Hibernate logs at WARN (will still show errors)
    org.springframework: WARN
