server:
  port: 8080

spring:
  datasource:
    username: root
    password: 12345678
    url: jdbc:mysql://localhost:3306/trivia
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    format_sql: true
    hibernate:
      ddl-auto: update
